// goivy/svk/src/lib/workbench/components/panes/EditorPane.svelte
<script lang="ts">
	import type { ModelDocument } from '$lib/types';

	type Props = {
		activeModel: ModelDocument;
		editorText: string;
		keymap: 'sublime' | 'emacs' | 'vim';
		onUpdateEditor: (text: string) => void;
		onSetKeymap: (keymap: 'sublime' | 'emacs' | 'vim') => void;
	};

	let { activeModel, editorText, keymap, onUpdateEditor, onSetKeymap }: Props = $props();
	const lineNumbers = $derived(editorText.split('\n').map((_, index) => index + 1));
</script>

<section class="pane editor-pane" aria-label="Editor">
	<div class="pane-title">
		<strong>Editing: {activeModel.filename} [{activeModel.dirty ? 'unsaved' : 'saved'}]</strong>
		<span data-testid="dirty-indicator">{activeModel.dirty ? 'Unsaved' : 'Saved'}</span>
	</div>
	<div class="editor-controls">
		<button type="button">x</button>
		<label><input type="radio" name="keymap" checked={keymap === 'sublime'} onchange={() => onSetKeymap('sublime')} /> Sublime</label>
		<label><input type="radio" name="keymap" checked={keymap === 'emacs'} onchange={() => onSetKeymap('emacs')} /> Emacs-ish</label>
		<label><input type="radio" name="keymap" checked={keymap === 'vim'} onchange={() => onSetKeymap('vim')} /> Vim</label>
		<a href="https://codemirror.net/5/doc/manual.html#keymaps" target="_blank" rel="noreferrer">keymap docs</a>
	</div>
	<div class="editor-wrap">
		<div class="line-gutter" aria-hidden="true">
			{#each lineNumbers as number (number)}
				<span>{number}</span>
			{/each}
		</div>
		<textarea
			id="model-editor"
			data-testid="model-editor"
			spellcheck="false"
			value={editorText}
			oninput={(event) => onUpdateEditor(event.currentTarget.value)}
		></textarea>
	</div>
</section>

// goivy/webui/frontend/src/components/panes/EditorPane.vue
<script setup>
import { useEditorStore } from '../../stores/editorStore.js';

const editorStore = useEditorStore();
</script>

<template>
  <div id="editor-panel">
    <div class="panel-header">
      <div class="editor-title-row">
        <strong class="column-title">Editing:</strong>
        <span id="model-editor-label" class="editor-path" :title="`Editing: ${editorStore.label}`">{{ editorStore.label }}</span>
      </div>
      <div class="panel-header-actions">
        <button id="file-close-current" class="editor-close-btn" title="Close current file">x</button>
        <button id="file-reopen-last" class="reopen-last-btn" style="display:none;"></button>
        <span class="keymap-radios">
          <label><input type="radio" name="keymap" value="sublime" checked> Sublime</label>
          <label><input type="radio" name="keymap" value="emacs"> Emacs-ish</label>
          <label><input type="radio" name="keymap" value="vim"> Vim</label>
          <a class="keymap-docs-link" href="https://codemirror.net/5/doc/manual.html#keymaps" target="_blank" rel="noopener noreferrer">keymap docs</a>
        </span>
      </div>
    </div>
    <textarea id="model-editor" class="model-editor-text" spellcheck="false" placeholder="Load an .ivy file to see its source here..."></textarea>
  </div>
</template>
