// goivy/webui/frontend/src/components/Menubar.vue
<template>
  <div id="menubar">
    <div class="menu-group">
      <div class="dropdown">
        <span class="panel-menu" data-dropdown="file-menu">File</span>
        <div id="file-menu" class="dropdown-content">
          <a href="#" id="file-load">Load...</a>
          <a href="#" id="file-open-event-trace">Open Event Trace...</a>
          <a href="#" id="file-save-as">Save as...</a>
          <a href="#" id="file-download">Download current model</a>
          <a href="#" id="file-save-analysis-state">Save Analysis State...</a>
          <a href="#" id="file-load-analysis-state">Load Analysis State...</a>
          <a href="#" id="file-save-invariant">Save Invariant...</a>
          <div class="dropdown-sep"></div>
          <RecentFilesMenu />
          <div class="dropdown-sep"></div>
          <div style="height:4px"></div>
          <a href="#" id="file-new">New Model</a>
        </div>
      </div>
    </div>
    <div class="menu-group">
      <span class="menu-label">Mode</span>
      <select id="mode-select">
        <option value="induction">Induction</option>
        <option value="pdr" selected>PDR</option>
        <option value="concrete">Concrete</option>
        <option value="abstract">Abstract</option>
        <option value="bounded">Bounded</option>
      </select>
    </div>
    <div class="menu-group">
      <button id="btn-check" class="menu-btn action-btn">Check</button>
      <button id="btn-show-reachable" class="menu-btn">Show Reachable</button>
      <button id="btn-undo" class="menu-btn">Undo</button>
      <button id="btn-reset-domain" class="menu-btn">Reset Domain</button>
      <button id="btn-diagram-domain" class="menu-btn">Diagram Domain</button>
      <span id="loaded-file" class="loaded-file"></span>
    </div>
    <div class="menu-group menu-right">
      <button id="btn-toggle-tutorial" class="menu-btn">Hide Tutorial</button>
    </div>
  </div>
</template>

<script setup>
import RecentFilesMenu from './RecentFilesMenu.vue';
</script>

// goivy/svk/src/lib/workbench/components/Menubar.svelte
<script lang="ts">
	import { FILE_MENU } from '$lib/workbench/commands/menuDefinitions';
	import type { SessionMode } from '$lib/workbench/state';

	type EngineChoice = 'hosted-go' | 'hosted-webui' | 'browser-wasm';

	type Props = {
		engineChoice: EngineChoice;
		mode: SessionMode;
		onActivateEngine: (choice: EngineChoice) => void | Promise<void>;
		onSetMode: (mode: SessionMode) => void;
		onRunCommand: (commandId: string) => void | Promise<void>;
	};

	let {
		engineChoice,
		mode,
		onActivateEngine,
		onSetMode,
		onRunCommand
	}: Props = $props();
</script>

<header class="topbar">
	<div class="dropdown">
		<button type="button" class="menu-button">File</button>
		<div class="dropdown-content">
			{#each FILE_MENU as item (item.id)}
				{#if item.separatorBefore}
					<div class="dropdown-sep"></div>
				{/if}
				<button type="button" onclick={() => void onRunCommand(item.commandId)}>{item.label}</button>
			{/each}
		</div>
	</div>
	<span class="mode-label">MODE</span>
	<select aria-label="Mode" class="mode-select" value={mode} onchange={(event) => onSetMode(event.currentTarget.value as SessionMode)}>
		<option value="induction">Induction</option>
		<option value="pdr">PDR</option>
		<option value="concrete">Concrete</option>
		<option value="abstract">Abstract</option>
		<option value="bounded">Bounded</option>
	</select>
	<select
		aria-label="Engine"
		class="engine-select"
		value={engineChoice}
		onchange={(event) => void onActivateEngine(event.currentTarget.value as EngineChoice)}
	>
		<option value="hosted-go">Native Go engine</option>
		<option value="browser-wasm">Browser wasm</option>
		<option value="hosted-webui">Legacy webui server</option>
	</select>
	<div class="toolbar" aria-label="Workspace commands">
		<button type="button" class="primary" data-testid="run-check" onclick={() => void onRunCommand('runCheck')}>
			Check
		</button>
		<button type="button" onclick={() => void onRunCommand('showReachableStates')}>Show Reachable</button>
		<button type="button" onclick={() => void onRunCommand('doUndo')}>Undo</button>
		<button type="button" onclick={() => void onRunCommand('resetDomain')}>Reset Domain</button>
		<button type="button" onclick={() => void onRunCommand('diagramDomain')}>Diagram Domain</button>
	</div>
	<button type="button" class="tutorial-button">Show Tutorial</button>
</header>
