// goivy/webui/frontend/src/components/panes/StateRelationsPane.vue
<script setup>
import { useStateRelationsStore } from '../../stores/stateRelationsStore.js';

const stateRelationsStore = useStateRelationsStore();

const columns = [
  { key: 'all_to_all', label: '+', title: (name) => `Show definite edges (${name})` },
  { key: 'edge_unknown', label: '?', title: (name) => `Show unknown edges (${name})` },
  { key: 'none_to_none', label: '-', title: (name) => `Show absent edges (${name})` },
  { key: 'transitive', label: 'T', title: (name) => `Transitive reduction (${name})` },
];
</script>

<template>
  <div id="state-panel" class="panel">
    <div class="panel-header">
      <strong class="column-title">State/relations</strong>
      <div class="panel-header-actions">
        <span id="state-label">State: {{ stateRelationsStore.stateLabel }}</span>
      </div>
    </div>
    <div id="state-controls">
      <table id="state-checkbox-table">
        <thead>
          <tr>
            <th class="chk-col">+</th>
            <th class="chk-col">?</th>
            <th class="chk-col">-</th>
            <th class="chk-col">T</th>
            <th class="name-col"></th>
          </tr>
        </thead>
        <tbody id="state-checkbox-body">
          <tr v-for="row in stateRelationsStore.rows" :key="row.name">
            <td v-for="column in columns" :key="column.key">
              <input
                type="checkbox"
                :title="column.title(row.name)"
                :checked="row.checked[column.key]"
                @change="stateRelationsStore.toggle(row.name, column.key, $event.target.checked)"
              >
            </td>
            <td class="name-col">
              <a href="#" @click.prevent>{{ row.name }}</a>
            </td>
          </tr>
          <tr v-if="stateRelationsStore.showPlaceholder">
            <td colspan="5" style="color:#666;font-style:italic;">No relations loaded</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

// goivy/svk/src/lib/workbench/components/panes/StateRelationsPane.svelte
<script lang="ts">
	import type { EdgeDisplayClass, NodeLabelDisplayClass } from '$lib/types';
	import type { StateRelationRow } from '$lib/state/stateRelations.svelte';

	type Props = {
		stateLabel: string;
		rows: StateRelationRow[];
		onToggle?: (rowId: string, displayClass: string, checked: boolean) => void | Promise<void>;
	};

	let { stateLabel, rows, onToggle }: Props = $props();
	const columns = [
		['all_to_all', '+'],
		['edge_unknown', '?'],
		['none_to_none', '-'],
		['transitive', 'T']
	] as const satisfies readonly [EdgeDisplayClass, string][];

	function checked(row: StateRelationRow, key: EdgeDisplayClass | NodeLabelDisplayClass) {
		return row.columns.find((column) => column.key === key)?.checked ?? false;
	}
</script>

<section class="pane state-pane" aria-label="State relations">
	<div class="pane-title">
		<strong>State/relations</strong>
	</div>
	<div class="state-panel">
		<strong>State: {stateLabel}</strong>
		<table id="state-checkbox-table" aria-label="Relation toggles">
			<thead>
				<tr>
					{#each columns as [, label] (label)}
						<th class="chk-col">{label}</th>
					{/each}
					<th class="name-col"></th>
				</tr>
			</thead>
			<tbody id="state-checkbox-body">
				{#if rows.length > 0}
					{#each rows as row (row.name)}
						<tr>
							{#each columns as [key] (key)}
								<td>
									<input
										type="checkbox"
										checked={checked(row, key)}
										onchange={(event) => void onToggle?.(row.id, key, event.currentTarget.checked)}
									/>
								</td>
							{/each}
							<td class="name-col">{row.name}</td>
						</tr>
					{/each}
				{:else}
					<tr>
						<td colspan="5" class="state-relations-empty">No relations loaded</td>
					</tr>
				{/if}
			</tbody>
		</table>
	</div>
</section>
