// goivy/webui/frontend/src/components/panes/TutorialPane.vue
<template>
  <div id="tutorial-container">
    <div class="panel-header tutorial-url-bar">
      <button id="tutorial-back" class="tutorial-nav-btn" title="Back">&#9664;</button>
      <button id="tutorial-fwd" class="tutorial-nav-btn" title="Forward">&#9654;</button>
      <button id="tutorial-reload" class="tutorial-nav-btn" title="Reload">&#8635;</button>
      <input id="tutorial-url" type="text" class="tutorial-url-input" value="/static/tutorial/kenmcmil.github.io/ivy/language.html" spellcheck="false">
      <button id="tutorial-close" class="tutorial-close-btn" title="Close tutorial">&#215;</button>
    </div>
    <iframe id="tutorial-iframe" class="tutorial-iframe" src="/static/tutorial/kenmcmil.github.io/ivy/language.html"></iframe>
  </div>
</template>

// goivy/svk/src/lib/workbench/components/panes/TutorialPane.svelte
<script lang="ts">
	type Props = {
		visible?: boolean;
		url?: string;
	};

	let { visible = false, url = '/static/tutorial/kenmcmil.github.io/ivy/language.html' }: Props = $props();
</script>

{#if visible}
	<section id="tutorial-container" aria-label="Tutorial">
		<div class="panel-header tutorial-url-bar">
			<button id="tutorial-back" type="button" class="tutorial-nav-btn">Back</button>
			<button id="tutorial-forward" type="button" class="tutorial-nav-btn">Forward</button>
			<input class="tutorial-url-input" value={url} aria-label="Tutorial URL" />
			<button id="tutorial-close" type="button" class="tutorial-close-btn">x</button>
		</div>
		<iframe id="tutorial-iframe" class="tutorial-iframe" title="Ivy tutorial" src={url}></iframe>
	</section>
{/if}
